name       : libtorrent
version    : 0.13.6
release    : 1
source     :
    - http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz : 2838a08c96edfd936aff8fbf99ecbb930c2bfca3337dd1482eb5fccdb80d5a04
license    : GPL-2.0
component  : programming.library
summary    : A BitTorrent library written in C++
description: |
    LibTorrent is a BitTorrent library written in C++ for *nix,
    with a focus on high performance and good code. The library 
    differentiates itself from other implementations by transfering
    directly from file pages to the network stack. On high-bandwidth
    connections it is able to seed at 3 times the speed of the official
    client.
builddeps  :
    - pkgconfig(libcrypto)
setup      : |
    %configure --disable-debug \
               --enable-ipv6 \
               --with-posix-fallocate
build      : |
    %make
install    : |
    %make_install
