name       : libtorrent
version    : 0.13.8
release    : 6
source     :
    - https://github.com/rakshasa/libtorrent/archive/v0.13.8.tar.gz : 0f6c2e7ffd3a1723ab47fdac785ec40f85c0a5b5a42c1d002272205b988be722
license    : GPL-2.0-or-later
component  : programming.library
summary    : A BitTorrent library written in C++
description: |
    LibTorrent is a BitTorrent library written in C++ for *nix, with a focus on high performance and good code. The library differentiates itself from other implementations by transfering directly from file pages to the network stack. On high-bandwidth connections it is able to seed at 3 times the speed of the official client.
setup      : |
    %reconfigure --disable-debug \
        --enable-ipv6 \
        --with-posix-fallocate
build      : |
    %make
install    : |
    %make_install
