name       : libtorrent
version    : 0.13.7
release    : 2
source     :
    - https://github.com/rakshasa/libtorrent/archive/v0.13.7.tar.gz : 86b4b1753385aaddf9e59ad94f1292eee5102139eb57520e84d1af2f04693708
license    : GPL-2.0-or-later
component  : programming.library
summary    : A BitTorrent library written in C++
description: "LibTorrent is a BitTorrent library written in C++ for *nix,\nwith a focus on high performance and good code. The library \ndifferentiates itself from other implementations by transfering\n\
    directly from file pages to the network stack. On high-bandwidth\nconnections it is able to seed at 3 times the speed of the official\nclient.\n"
builddeps  :
    - pkgconfig(libcrypto)
setup      : |
    %reconfigure --disable-debug \
               --enable-ipv6 \
               --with-posix-fallocate
build      : |
    %make
install    : |
    %make_install
